---
  title: "VegVisions-HWSMidterm"
author: "Sacha Jellinek"
date: "20/06/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE, warning=FALSE}
library(sf)
library(tmap)
library(skimr)
library(visdat)
library(lubridate) # for as_date()
library(tidyverse)
library(viridis)
library(ggrepel)
library(ggspatial)
library(xlsx)
#library(s2)
library(tiff)
library(raster)
library(glmmTMB)
library(lme4)
library(emmeans)
library(MuMIn)
library(sjPlot)
library(multcomp)
#library(wesanderson)

```

## VegVisions data for HWS Mid-term
#This script:    
#  i) reads in, explores and tidies Survivorship data collected by SJellinek Nov 2021

Mon_data <- st_read("~/uomShare/wergProj/ROMP_Survivorship_2021/Data/survival_data_180322.csv")
str(Mon_data)
names(Mon_data)
loc_data <- st_read("~/uomShare/wergProj/ROMP_Survivorship_2021/ROMP_2021_sites.shp")
MW_bound <- st_read("~/uomShare/wergProj/VegVisions/Mapping/MW Catchments/HWS_Catchments2.shp")
Aridity_base <- st_read("~/uomShare/wergProj/VegVisions/Mapping/Aridity change/Aridity_baseline_1986_2005avg.shp")
Aridity_base <- st_transform(Aridity_base,  crs = st_crs(loc_data))
MW_subcatch <- st_read ("~/uomShare/wergProj/VegVisions/Mapping/MW Catchments/HWS_Subcatchments_region.shp")
sites_aridity <- st_join(loc_data, Aridity_base, left = FALSE) %>% 
  dplyr::select(site, CATCHMENT, SUBCATCHME, MEAN)
#points = st_as_sf(loc_data, coords = c("Eastings", "Northings"), crs = utmCRS)
#st_crs(points)

df <- left_join(Mon_data, sites_aridity, by = 'site')
str(df)

Fig0 <- ggplot() +
 # geom_sf(data = waterways, fill = "NA", colour = "blue", size = 0.4) +
  geom_sf(data = loc_data, fill = "NA", color = "red", size = 2) +
  geom_sf(data = MW_bound, fill = "NA", color = "black", size = 1) +
  geom_sf_text(data = MW_bound, aes(label = CATCHMENT), colour = "black",
               nudge_x =c(-0.3, 0.2, 0.615, -0.3, -0.36),
               nudge_y = c(-0.05, 0.2, 0.01, 0.4, 0.3)) + 
  annotation_scale(location = "bl", width_hint = 0.4) +
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  xlab("Longitude") + ylab("Latitude") + theme_classic() +
  guides(colour=guide_legend(title = "Vegetation Visions Score"))
Fig0


dat <- df %>% 
  dplyr::mutate(belt = as.integer(belt), 
                alive = as.integer(alive), 
                total = as.integer(total), 
                height = as.numeric(height), 
                weeds = as.numeric(weeds))
str(dat)
dat <- dat %>% 
  mutate(weeds2 = (weeds/100))

sp_abun1 <- dat %>% 
  group_by(site, catchment, belt, lifeform, pests, weeds2, guard, MEAN) %>%
  summarise_at(vars(total, alive), tibble::lst(mean, median))
summaryabun <- sp_abun1 %>% mutate(percent=alive_mean/total_mean)
summaryabun

sp_abun1 <- summaryabun %>% 
  group_by(catchment) %>%
  mutate(Count = n()) %>%
  summarise_at(vars(percent), funs(mean, sd, se=sd(.)/sqrt(n())))
sp_abun1

#Bar plot of species survival by catchment

fig1 <- ggplot(sp_abun1, aes(x = reorder(catchment, -mean), y = mean)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), 
                width=.2,
                position=position_dodge(.9)) +
  labs(y = "Percent survival per site", x = "Melbourne Water Catchment") +
  theme_classic() + theme(legend.position = c(0.8, 0.8)) +
  theme(axis.text.x = element_text(size = 9, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 9), axis.title.x = element_text(size=9),
        axis.title.y = element_text(size=9), legend.title=element_text(size=9), 
        legend.text=element_text(size=9))

fig1

#  factors in the model
summaryabun$catchment <- as.factor(summaryabun$catchment)
summaryabun$site <- as.factor(summaryabun$site)
summaryabun$guard <- as.factor(summaryabun$guard)
summaryabun$pests <- as.factor(summaryabun$pests)
summaryabun$lifeform <- as.factor(summaryabun$lifeform)
str(summaryabun)

#summaryabun$percent[summaryabun$percent >= 1] <- 1
lmecon <- glmmTMB((percent + 0.01)/1.02 ~ MEAN + pests + weeds2 + guard + (1|site), data = summaryabun, family = 'beta_family')
summary(lmecon) # change in condition 
r.squaredGLMM(lmecon)
plot_model(lmecon)
coef(lmecon)

surv1_mod <- glmmTMB(cbind(alive_mean, total_mean) ~ MEAN + pests + weeds2 + guard + (1|site), data = summaryabun, family = "quasibinomial")
summary(surv1_mod) # change in condition 
plot_model(surv1_mod)

overdisp_glmm <- function(surv1_mod) {
  ## number of variance parameters in 
  ##   an n-by-n variance-covariance matrix
  vpars <- function(m) nrow(m)*(nrow(m)+1)/2
  
  model.df <- sum(sapply(lme4::VarCorr(surv1_mod),vpars))+length(lme4::fixef(surv1_mod))
  rdf <- nrow(model.frame(surv1_mod))-model.df
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(Pearson.chisq, df=rdf, lower.tail=FALSE)
  c(chisq=Pearson.chisq,ratio=prat,rdf=rdf,p=pval)
}
Lfmodel = lm(percent ~ MEAN, data = summaryabun)
aov(Lfmodel)
marginal = lsmeans(Lfmodel, ~ MEAN)
CLD = cld(marginal, alpha=0.05, Letters=letters, adjust="tukey")
CLD
CLD$.group=gsub(" ", "", CLD$.group)

heightdata <- dat %>% 
  group_by(site, catchment, belt, lifeform, species, pests, weeds2, guard) %>%
  summarise_at(vars(height), tibble::lst(mean, median), na.rm = TRUE)
heightdata <- filter(heightdata, lifeform != 'Forb')
heightdata <- filter(heightdata, lifeform != 'Tussock grass')
heightdata <- filter(heightdata, lifeform != 'Fern')
# graph raw heights using boxplots?

heightfig <- ggplot(
  data = heightdata, aes(x = reorder(catchment, -mean), y = mean, fill = lifeform)) +
  geom_boxplot() +
  labs(y = "Plant Heights (m)", x = "Melbourne Water Catchment") +
  theme_classic() + theme(legend.position = c(0.8, 0.8)) +
  theme(axis.text.x = element_text(size = 9, angle = 45, hjust = 1),
        axis.text.y = element_text(size = 9), axis.title.x = element_text(size=9),
        axis.title.y = element_text(size=9), legend.title=element_text(size=9), 
        legend.text=element_text(size=9))
#labs(x= NULL, y = "Height (m)")
# theme_classic() +
# theme(axis.ticks.x = element_blank()) +
# theme(axis.text.x = element_text(angle = 90))
heightfig

lmecon <- glmmTMB(mean ~ guard + pests + weeds2 + (1|site), data = heightdata)
summary(lmecon) # change in condition 
r.squaredGLMM(lmecon)
plot_model(lmecon)
coef(lmecon)

############################ Individual Species ##########################################
Mon_data2 <- filter(Mon_data, species != 'Dead Unknown')
Indiv_data <- Mon_data2 %>%
  group_by(site, species, lifeform) %>%
  summarise_at(vars(total, alive), tibble::lst(mean, median))

cma_sp <- Mon_data2 %>% 
  group_by(species, catchment) %>%
  summarise(number = n()) %>% tally(sort = T)

#calculate the mean and CI for alive and total
spdata_sp <- Indiv_data %>%
  group_by(species, lifeform) %>%
  summarise(n = n(), 
            meantotal = mean(total_mean),
            setotal = sd(total_mean)/sqrt(n()),
            meanalive = mean(alive_mean),
            sealive = sd(alive_mean)/sqrt(n()))
Rich <- spdata_sp %>%
  mutate(surv = meanalive / meantotal)
#remove all species recorded at only 1 CMA
#Rich <- filter(Rich, n != '1')
#Rich <- filter(Rich, n != '2')
# order by abundance
spdata_sp <- Rich %>%
  arrange(desc(-surv))

#combine the 2 tables by species and arrange by CMA
Species_data <- full_join(spdata_sp, cma_sp, by = "species") %>%
  arrange(desc(n.y))

# cut the first 20 rows
Data_sp16 <-Species_data[1:16,]
tail(Data_sp16)
Data_sp16 <- dplyr::select (Data_sp16,-c(n.y))
Data_sp16 <- dplyr::select (Data_sp16,-c(surv))
#which(is.na(Sp_reshapeses))

# reshaping of data (this is pretty messy sorry)
Sp_reshape <- gather(Data_sp16, key = "variable", value = "mean", -c(species, lifeform, n.x, setotal, sealive))
Sp_reshape <- subset(Sp_reshape, select = -c(setotal, sealive))
Sp_reshapeses <- gather(Data_sp16, key = "variable", value = "error", -c(species, lifeform, n.x, meantotal, meanalive))
Sp_reshape$error <- Sp_reshapeses$error
Sp_reshape <- as.data.frame(Sp_reshape)

## Question - how do I include CI in this plot
Sp_reshape$variable <- factor(Sp_reshape$variable, levels = c("meantotal", "meanalive"))
Sp_reshape$lifeform <- as.factor(Sp_reshape$lifeform)

#reorder by lifeform, variable and mean (heighest to lowest)
Sp_reshape <- Sp_reshape[with(Sp_reshape, order(lifeform, variable, -mean)),]
Sp_reshape$species <- factor(Sp_reshape$species, levels = unique(Sp_reshape$species))
#ggsave(path = path, width = width, height = height, device='jpeg', dpi=300)

fig3 <- ggplot(Sp_reshape, aes(x = species, y = mean, fill = variable)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=mean-error, ymax=mean+error), 
                width=.2,
                position=position_dodge(.9)) +
  facet_grid(~ lifeform, scales = "free_x", space = "free") +
  scale_fill_grey(start = 0.8, end = 0.6, name="Individual plant counts", breaks=c("meantotal", "meanalive"),
                  labels=c("Total plants", "Alive plants")) + 
  #scale_x_discrete(labels=c("Ozothamnus ferrugineus" = "Ozo. ferrugineus", "Leptospermum continentale" = "Lepto. continentale",
  #                          "Leptospermum lanigerum" = "Lepto. lanigerum", "Cassinia aculeata subsp. aculeata" = "Cassinia aculeata", 
  #                          "Allocasuarina verticillata" = "Allo. verticillata", 
  #                          "Acacia verniciflua s.l." = "Acacia verniciflua")) +
  labs(y = "Mean abundance per site", x = "Species") +
  theme_classic() + theme(legend.position = c(0.7, 0.8)) +
  theme(axis.text.x = element_text(size = 9, angle = 55, hjust = 1),
        axis.text.y = element_text(size = 9), axis.title.x = element_text(size=9),
        axis.title.y = element_text(size=9), legend.title=element_text(size=9), 
        legend.text=element_text(size=9))
fig3


############################ Individual Species ##########################################
Mon_data2 <- filter(Mon_data, species != 'Dead Unknown')
Indiv_data <- Mon_data2 %>%
  group_by(site, catchment, species, lifeform) %>%
  summarise_at(vars(total, alive), tibble::lst(mean, median))
Indiv_data <- filter(Indiv_data, catchment == 'Werribee')

#calculate the mean and CI for alive and total
spdata_sp <- Indiv_data %>%
  group_by(species, lifeform) %>%
  summarise(n = n(), 
            meantotal = mean(total_mean),
            setotal = sd(total_mean)/sqrt(n()),
            meanalive = mean(alive_mean),
            sealive = sd(alive_mean)/sqrt(n()))
Rich <- spdata_sp %>%
  mutate(surv = meanalive / meantotal)
#remove all species recorded at only 1 CMA

# order by abundance
spdata_sp <- Rich %>%
  arrange(desc(n))

#combine the 2 tables by species and arrange by CMA
#Species_data <- arrange(desc(n.x))

# cut the first 20 rows
Data_sp16 <-Species_data[1:10,]
tail(Data_sp16)
Data_sp16 <- dplyr::select (Data_sp16,-c(n.y))
Data_sp16 <- dplyr::select (Data_sp16,-c(surv))
#which(is.na(Sp_reshapeses))

# reshaping of data (this is pretty messy sorry)
Sp_reshape <- gather(Data_sp16, key = "variable", value = "mean", -c(species, lifeform, n.x, setotal, sealive))
Sp_reshape <- subset(Sp_reshape, select = -c(setotal, sealive))
Sp_reshapeses <- gather(Data_sp16, key = "variable", value = "error", -c(species, lifeform, n.x, meantotal, meanalive))
Sp_reshape$error <- Sp_reshapeses$error
Sp_reshape <- as.data.frame(Sp_reshape)

## Question - how do I include CI in this plot
Sp_reshape$variable <- factor(Sp_reshape$variable, levels = c("meantotal", "meanalive"))
Sp_reshape$lifeform <- as.factor(Sp_reshape$lifeform)

#reorder by lifeform, variable and mean (heighest to lowest)
Sp_reshape <- Sp_reshape[with(Sp_reshape, order(lifeform, variable, -mean)),]
Sp_reshape$species <- factor(Sp_reshape$species, levels = unique(Sp_reshape$species))
#ggsave(path = path, width = width, height = height, device='jpeg', dpi=300)

fig3 <- ggplot(Sp_reshape, aes(x = species, y = mean, fill = variable)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=mean-error, ymax=mean+error), 
                width=.2,
                position=position_dodge(.9)) +
  facet_grid(~ lifeform, scales = "free_x", space = "free") +
  scale_fill_grey(start = 0.8, end = 0.6, name="Individual plant counts", breaks=c("meantotal", "meanalive"),
                  labels=c("Total plants", "Alive plants")) + 
  labs(y = "Mean abundance per site", x = "Species") +
  theme_classic() + theme(legend.position = c(0.7, 0.8)) +
  theme(axis.text.x = element_text(size = 9, angle = 55, hjust = 1),
        axis.text.y = element_text(size = 9), axis.title.x = element_text(size=9),
        axis.title.y = element_text(size=9), legend.title=element_text(size=9), 
        legend.text=element_text(size=9))
fig3